version: '3'
services:
  api:
    container_name: flask-container
    build: .
    image: flask-app
    ports:
      - "5000:5000"

  database:
    image: postgres
    container_name: database-container
    environment:
      - POSTGRES_USER=unbxd
      - POSTGRES_PASSWORD=unbxd
      - POSTGRES_DB=unbxddatabase
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"