apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: dheerajsreddy/my-app-image:latest 
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 5000          # Port exposed inside the cluster
      targetPort: 5000    # Port to forward the traffic to within the pod
      nodePort: 30000     # Port to access the service from outside the cluster


