apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask
  ports:
    - name: flask-port
      protocol: TCP
      port: {{ .Values.flask.port }}
      targetPort: {{ .Values.flask.port }}
  type: LoadBalancer
