apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres-container
          image: {{ .Values.postgres.image }}
          env:
            - name: POSTGRES_USER
              value: unbxd
            - name: POSTGRES_PASSWORD
              value: unbxd
            - name: POSTGRES_DB
              value: unbxddatabase
          ports:
            - containerPort: {{ .Values.postgres.port }}
