# Default values for flask-chart.
# These values can be overridden by providing a custom values.yaml or using --set during helm install/upgrade.
#This file will store configuration values that can be overridden during deployment.
# Declare variables to be passed into your templates.

replicaCount: 1

flask:
  image: dheerajsreddy/flask-app
  imagePullPolicy: Always
  port: 5000

redis:
  image: redis
  port: 6379

postgres:
  image: postgres
  port: 5432

ingress:
  enabled: true
  hostname: "apparel.com"

# You can add more configuration options as needed.
